### ISSUE TITLE
https://opendata.digilugu.ee/

### ISSUE THREAD

**Issue by armislv** [okestonia/koroonakaart#273]
Who knows what is happening with https://opendata.digilugu.ee? It is extremely unstable last months and now seems is dead.
Latest data is for Jan 29.

**Comment by neuroactive** [comment]
The open data portal is managed by TEHIK. They had some capacity problems due to the fact that the data files related to Covid had grown extremely large. This was causing some instability in the availability of the data and so they took the data offline for about a week to work on a solution. We have now been assured that the problems are fixed and the data is live again, so I will close this issue.
