### ISSUE TITLE
Irregular and incorrect updates

### ISSUE THREAD

**Issue by sonnichjensen** [okestonia/koroonakaart#274]
During the last week and a bit more, updates have not be daily, and updates has been incorrect. Updates have been 0 which is not true.

Even today, the 4th, I see that last update was on the 2nd and that number was 0, which is wrong.

Why is the page not being updated properly anymore?

**Comment by neuroactive** [comment]
Unfortunately there are currently problems with the source data published by TEHIK, which has meant that fresh data has been unavailable for several days. The problems are related to the fact that the data files have now grown extremely large. They are working on a solution, but they have notified us that it is likely to be a few days until that is ready. The situation isn't ideal, but the problem is out of our hands and so there is nothing we can do to speed things up I'm afraid.

**Comment by Zaaset** [comment]
How about adding a temporary fallback sources?
For example:
https://www.worldometers.info/coronavirus/country/estonia/
https://www.google.com/search?q=covid+vaccination+estonia

**Comment by neuroactive** [comment]
I will ask TEHIK how much longer the outage in the open data is going to last. If it's going to be a while, then we can add some kind of notice to the site explaining why it hasn't been updated, which will also need to be translated. If the open data is going to return to normal operation soon then it probably isn't worth it.

Incidentally, the vaccination data for Estonia in Google and their source Our World in Data doesn't appear to have been updated since 2 February, so presumably they are also relying on the open data which is currently unavailable.

**Comment by neuroactive** [comment]
We have been assured by TEHIK that the problems with the open data have been resolved. If today's update goes without any problems then I will close this issue.

**Comment by sonnichjensen** [comment]
And as of now, it is not worked for 2 days

**Comment by Zaaset** [comment]
> And as of now, it is not worked for 2 days

I was going to report that today also.
Especially since its 8K new cases and 17 deaths today

https://www.worldometers.info/coronavirus/country/estonia/

**Comment by sonnichjensen** [comment]
Still not working...

**Comment by neuroactive** [comment]
Unfortunately the process to update the data for the site has been running out of memory due to the ever-increasing size of the data files. I have a solution in mind so am going to work on implementing that today.

**Comment by neuroactive** [comment]
I have carried out some optimisation of the code, which I should fix the problems with updating the data. I have successfully tested the update process and the site has been updated with the latest data from today, so I will close this issue now. If any other problem arises with the data update, then please open a new issue.
