### ISSUE TITLE
hospitalizations and deaths charts very important  but missing (removed)

### ISSUE THREAD

**Issue by sheliphron** [okestonia/koroonakaart#275]
It is not very transparent removing hositalizations and death charts that are essential to describe the actual sanitary situation. Hospitalizations and deaths are much lower now than last autumn but maybe  politically is convenient to omit that to sustain the  restrictions infront of public opinion showing the  (mild) new cases chart only. I hope you reintroduce this missing information so users have not to search on foreigners sites forthose omitted datas  . https://graphics.reuters.com/world-coronavirus-tracker-and-maps/countries-and-territories/estonia/

**Comment by kristianheljas** [comment]
This is already discussed in https://github.com/okestonia/koroonakaart/issues/272.

In short, hospitalization data was removed due to performance problems (the data files grew too large) and some logic issues how the data was visualised, read more here: https://github.com/okestonia/koroonakaart/issues/272#issuecomment-1005505450

**Comment by neuroactive** [comment]
I do plan to restore the data on deaths and hospitalisations as soon as I can. It's taking a little longer than expected due to some technical issues I encountered and some other commitments I had to attend to. I'm closing this issue as it's covered by #272.
