### ISSUE TITLE
No updates again

### ISSUE THREAD

**Issue by sonnichjensen** [okestonia/koroonakaart#283]
Latest update:

Uuendatud: 03/05/2022, 21:00

Is contact to the database lost?

**Comment by neuroactive** [comment]
Terviseamet have changed the frequency with which they publish Covid-related data to once per week (on Tuesdays), and have also apparently discontinued publishing any new data related to hospitalisation. These changes were unfortunately made without any prior warning, and so the first I learned about it was when the daily update to the site stopped working. The update to the site which should have happened on Tuesday 10 May wasn't successful because the hospitalisation data it expects wasn't available. I am going to work on removing the dependency on the hospitalisation data this weekend so that the updates start working again.

**Comment by sonnichjensen** [comment]
Any news?

**Comment by neuroactive** [comment]
The open data related to hospitalisation has resumed being published and the site has been updated. The figure for the increase in deaths (+5) relates to the past week as that is how frequently the source data is being updated now.
